services:
  gin:
    build:
      context: .
      dockerfile: Dockerfile.gin
    ports:
      - "8080:8080"

  http:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "8090:8090"
