FROM golang:1.21-alpine AS build

WORKDIR /app

COPY go.mod  go.sum  ./

RUN go mod download

COPY . .

RUN go build -o ./gin ./cmd/gin/main.go

FROM scratch

WORKDIR /app

COPY --from=build /app/gin ./gin 

EXPOSE 8080

CMD ["./gin"]