apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
  namespace: {{.Values.ns}}
spec:
  selector:
    app: {{.Values.servername}}
  ports:
    - protocol: TCP
      port: {{.Values.port}}
      targetPort: {{.Values.port}}